version: '3'
services:
  api:
    container_name: phoenix_api
    build: ./docker_config
    ports:
      - "4000:4000"
    volumes:
      - ./src:/src
    depends_on:
      - db
  db:
    container_name: phoenix_db
    image: "postgres:12.2"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  db-data:
