version: '3'
services:
  api:
    container_name: phoenix_api
    build: ./docker_config
    ports:
      - "4000:4000"
    volumes:
      - ./src:/src
      - vol_deps:/src/deps
      - vol_node_modules:/src/assets/node_modules
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: phoenix_db
    image: "postgres:12.2"
    volumes:
      - vol_db:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  vol_deps:
  vol_node_modules:
  vol_db:
